name: pntools
channels:
  - defaults
  - conda-forge
dependencies:
  - blinker
  - ffmpeg-python
  - matplotlib
  - multiprocess
  - numpy
  - opencv
  - pandas
  - pip
  - scipy
  - pyfilemanager
  - pip:
      - decord
